name = "edge-server-boilerplate"
compatibility_date = "2023-01-01"

[env.dev.vars]
DATABASE_URL = "libsql://..."

[env.production.vars]
API_HOST = "production.example.com"

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""
